[package]
name = "gxib"
version = "0.1.3-rc.1"
authors = ["aniketfuryrocks <prajapati.ani306@gmail.com>"]
edition = "2018"
description = "build tool for the gxi-rs project"
repository = "https://github.com/gxi-rs/gxib.git"
license = "MIT"
keywords = ["gxi-rs", "build-tool"]
categories = ["command-line-utilities", "development-tools::build-utils", "web-programming"]

[workspace]
members = ["examples/web", "examples/desktop"]

[dependencies]
clap = "3.0.0-beta.2"
notify = "5.0.0-pre"
anyhow = "1.0.40"
seahash = "4.1.0"
path-absolutize = "3.0.10"
futures = "0.3.15"
actix-web = "3"
actix-web-actors = "3"
actix-files = "0.5.0"
actix = "0.10"

[dependencies.toml]
version = "0.5.8"
features = ["preserve_order"]

[dependencies.tokio]
version = "1"
features = ["full", "process"]

