[package]
name = "web"
version = "0.1.0"
authors = ["aniketfuryrocks <prajapati.ani306@gmail.com>"]
edition = "2018"

[dependencies]
wee_alloc = "0.4.5"

[dependencies.gxi]
path = "../../../gxi"
version = ""
features = ["web"]
