[package]
name = "web"
version = "0.1.0"
authors = ["aniketfuryrocks <contact@aniketprajapati.me>"]
edition = "2018"

[dependencies]
wee_alloc = "0.4.5"
gxi = { version = "0.4.0", features = ["web"] }
